sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-testing.txt --use-mirrors
script: nosetests --with-coverage --cover-erase --cover-package=enki
after_success:
  - pip install coveralls --use-mirrors
  - coveralls
