language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-testing.txt --use-mirrors
  - pip install coveralls --use-mirrors
script: nosetests --with-coverage --cover-erase --cover-package=enki
notifications:
  email: false
  irc: "irc.freenode.net#okfn-dev"
after_success:
  - coveralls
