sudo: false
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt 
  - pip install -r requirements-testing.txt 
script: nosetests --with-coverage --cover-erase --cover-package=enki
after_success:
  - pip install coveralls 
  - coveralls
